<?php
require_once __DIR__.'/../config/bootstrap.php';require_once __DIR__.'/../models/Competition.php';require_admin();
if($_SERVER['REQUEST_METHOD']!=='POST')json_error('Método no permitido',405);verify_csrf();
$a=(string)($_POST['action']??'');$pdo=db();
try{
 if($a==='patrol_save'){$id=(int)($_POST['id']??0);$numero=filter_var($_POST['numero']??null,FILTER_VALIDATE_INT);$nombre=trim((string)($_POST['nombre']??''));if(!$numero||$nombre==='')throw new DomainException('Número y nombre son obligatorios.');if($id){$q=$pdo->prepare('UPDATE patrullas SET numero=?,nombre=?,unidad=? WHERE id=?');$q->execute([$numero,$nombre,trim((string)($_POST['unidad']??'')),$id]);}else{$q=$pdo->prepare('INSERT INTO patrullas(competencia_id,categoria_id,numero,nombre,unidad)VALUES(1,1,?,?,?)');$q->execute([$numero,$nombre,trim((string)($_POST['unidad']??''))]);$id=(int)$pdo->lastInsertId();}audit($a,'patrullas',$id);}
 elseif($a==='patrol_delete'){$id=(int)$_POST['id'];$pdo->prepare('UPDATE patrullas SET activa=0 WHERE id=?')->execute([$id]);audit($a,'patrullas',$id);}
 elseif($a==='penalty_type_save'){$n=trim((string)($_POST['nombre']??''));$s=filter_var($_POST['segundos']??null,FILTER_VALIDATE_INT);if($n===''||$s===false||$s<0)throw new DomainException('Nombre y segundos válidos son obligatorios.');$q=$pdo->prepare('INSERT INTO tipos_penalizacion(competencia_id,nombre,segundos,observacion)VALUES(1,?,?,?)');$q->execute([$n,$s,trim((string)($_POST['observacion']??''))]);audit($a,'tipos_penalizacion',(int)$pdo->lastInsertId());}
 elseif($a==='penalty_add'){$pid=(int)$_POST['patrulla_id'];$tid=(int)$_POST['tipo_id'];$q=$pdo->prepare('SELECT segundos FROM tipos_penalizacion WHERE id=? AND activo=1');$q->execute([$tid]);$s=$q->fetchColumn();if($s===false)throw new DomainException('Penalización inválida.');$q=$pdo->prepare('INSERT INTO penalizaciones(patrulla_id,tipo_penalizacion_id,segundos,observacion,usuario_id)VALUES(?,?,?,?,?)');$q->execute([$pid,$tid,$s,trim((string)($_POST['observacion']??'')),user()['id']]);Competition::recalculate($pid);audit($a,'penalizaciones',(int)$pdo->lastInsertId());}
 elseif($a==='penalty_delete'){$id=(int)$_POST['id'];$q=$pdo->prepare('SELECT patrulla_id FROM penalizaciones WHERE id=?');$q->execute([$id]);$pid=(int)$q->fetchColumn();$pdo->prepare('DELETE FROM penalizaciones WHERE id=?')->execute([$id]);if($pid)Competition::recalculate($pid);audit($a,'penalizaciones',$id);}
 elseif($a==='user_save'&&user()['rol']==='admin'){$email=strtolower(trim((string)$_POST['email']));$name=trim((string)$_POST['nombre']);$pass=(string)($_POST['password']??'');$rol=in_array($_POST['rol']??'',['admin','juez','consulta'],true)?$_POST['rol']:'juez';if(!filter_var($email,FILTER_VALIDATE_EMAIL)||$name===''||strlen($pass)<10)throw new DomainException('Datos inválidos; la clave requiere 10 caracteres.');$q=$pdo->prepare('INSERT INTO usuarios(nombre,email,password_hash,rol)VALUES(?,?,?,?)');$q->execute([$name,$email,password_hash($pass,PASSWORD_DEFAULT),$rol]);audit($a,'usuarios',(int)$pdo->lastInsertId());}
 else throw new DomainException('Operación inválida.');
 json_out(['ok'=>true]);
}catch(Throwable $e){json_error($e instanceof DomainException?$e->getMessage():'No se pudo guardar. Verifique datos duplicados.',422);}

