CREATE DATABASE IF NOT EXISTS cai2026 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE cai2026;
CREATE TABLE competencias(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,nombre VARCHAR(150) NOT NULL,anio SMALLINT NOT NULL,estado ENUM('preparacion','en_curso','pausada','finalizada') DEFAULT 'preparacion',activa TINYINT(1) DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)ENGINE=InnoDB;
CREATE TABLE categorias(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,competencia_id INT UNSIGNED NOT NULL,nombre VARCHAR(100) NOT NULL,FOREIGN KEY(competencia_id)REFERENCES competencias(id))ENGINE=InnoDB;
CREATE TABLE pruebas(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,competencia_id INT UNSIGNED NOT NULL,nombre VARCHAR(120) NOT NULL,orden INT DEFAULT 0,FOREIGN KEY(competencia_id)REFERENCES competencias(id))ENGINE=InnoDB;
CREATE TABLE usuarios(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,nombre VARCHAR(120) NOT NULL,email VARCHAR(190) NOT NULL UNIQUE,password_hash VARCHAR(255),google_sub VARCHAR(190) UNIQUE,rol ENUM('admin','juez','consulta') DEFAULT 'juez',activo TINYINT(1) DEFAULT 1,ultimo_acceso DATETIME,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)ENGINE=InnoDB;
CREATE TABLE patrullas(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,competencia_id INT UNSIGNED NOT NULL,categoria_id INT UNSIGNED,numero INT NOT NULL,nombre VARCHAR(120) NOT NULL,unidad VARCHAR(150),color VARCHAR(20) DEFAULT '#38bdf8',estado ENUM('espera','en_curso','finalizada','retirada') DEFAULT 'espera',activa TINYINT(1) DEFAULT 1,UNIQUE(competencia_id,numero),FOREIGN KEY(competencia_id)REFERENCES competencias(id),FOREIGN KEY(categoria_id)REFERENCES categorias(id)ON DELETE SET NULL)ENGINE=InnoDB;
CREATE TABLE competidores(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,patrulla_id INT UNSIGNED NOT NULL,nombre VARCHAR(150) NOT NULL,documento VARCHAR(30),funcion VARCHAR(80),FOREIGN KEY(patrulla_id)REFERENCES patrullas(id)ON DELETE CASCADE)ENGINE=InnoDB;
CREATE TABLE cronometro_global(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,competencia_id INT UNSIGNED NOT NULL UNIQUE,fecha_hora_inicio DATETIME(6),fecha_hora_pausa DATETIME(6),tiempo_pausado_acumulado BIGINT UNSIGNED DEFAULT 0 COMMENT 'microsegundos',estado ENUM('detenido','en_curso','pausado','finalizado') DEFAULT 'detenido',fecha_hora_fin DATETIME(6),FOREIGN KEY(competencia_id)REFERENCES competencias(id))ENGINE=InnoDB;
CREATE TABLE tiempos(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,patrulla_id INT UNSIGNED NOT NULL UNIQUE,prueba_id INT UNSIGNED,fecha_hora_salida DATETIME(6),fecha_hora_llegada DATETIME(6),FOREIGN KEY(patrulla_id)REFERENCES patrullas(id)ON DELETE CASCADE,FOREIGN KEY(prueba_id)REFERENCES pruebas(id)ON DELETE SET NULL)ENGINE=InnoDB;
CREATE TABLE tipos_penalizacion(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,competencia_id INT UNSIGNED NOT NULL,nombre VARCHAR(150) NOT NULL,segundos INT UNSIGNED NOT NULL,observacion VARCHAR(255),activo TINYINT(1) DEFAULT 1,FOREIGN KEY(competencia_id)REFERENCES competencias(id))ENGINE=InnoDB;
CREATE TABLE penalizaciones(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,patrulla_id INT UNSIGNED NOT NULL,tipo_penalizacion_id INT UNSIGNED,segundos INT UNSIGNED NOT NULL,observacion VARCHAR(255),usuario_id INT UNSIGNED,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(patrulla_id)REFERENCES patrullas(id)ON DELETE CASCADE,FOREIGN KEY(tipo_penalizacion_id)REFERENCES tipos_penalizacion(id)ON DELETE SET NULL,FOREIGN KEY(usuario_id)REFERENCES usuarios(id)ON DELETE SET NULL)ENGINE=InnoDB;
CREATE TABLE resultados(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,patrulla_id INT UNSIGNED NOT NULL UNIQUE,tiempo_bruto_segundos INT UNSIGNED,penalizaciones_segundos INT UNSIGNED DEFAULT 0,tiempo_final_segundos INT UNSIGNED,posicion INT UNSIGNED,actualizado_en DATETIME,FOREIGN KEY(patrulla_id)REFERENCES patrullas(id)ON DELETE CASCADE)ENGINE=InnoDB;
CREATE TABLE historial(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,usuario_id INT UNSIGNED,fecha_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,accion VARCHAR(100) NOT NULL,entidad VARCHAR(80),entidad_id INT UNSIGNED,detalle JSON,ip VARCHAR(45) NOT NULL,INDEX(fecha_hora),FOREIGN KEY(usuario_id)REFERENCES usuarios(id)ON DELETE SET NULL)ENGINE=InnoDB;
INSERT INTO competencias(nombre,anio)VALUES('Competencia Andina Invernal',2026);
INSERT INTO categorias(competencia_id,nombre)VALUES(1,'General');
INSERT INTO cronometro_global(competencia_id)VALUES(1);
INSERT INTO tipos_penalizacion(competencia_id,nombre,segundos,observacion)VALUES(1,'Blanco omitido',30,'Por cada blanco'),(1,'Material faltante',120,NULL),(1,'Error de navegación',300,NULL),(1,'Ayuda externa',600,NULL);
-- Crear el primer administrador con: php tools/create_admin.php correo@gmail.com "Nombre"

